name: Deploy Docs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Generate docs
        run: crystal docs
      - name: Publish the docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs